export const GET_MOVIES = 'GET_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

export const GETTING_MOVIE = 'GETTING_MOVIE';
export const GET_TOP_FOUR_MOVIES = 'GET_TOP_FOUR_MOVIES';
export const GET_TOP_MOVIES = 'GET_TOP_MOVIES';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';

export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAIL = 'GET_MOVIE_DETAILS_FAIL';

export const MODIFY_CURRENT_MOVIE_PAGE = 'MODIFY_CURRENT_MOVIE_PAGE';